#cloud-config

packages:
  - docker.io

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  - sudo curl -L git.io/weave -o /usr/local/bin/weave
  - sudo chmod a+x /usr/local/bin/weave

  - weave launch ${cfg-primary}
  - eval $(weave env)
  
  - /usr/bin/docker pull bitnami/mongodb-sharded
  - >
    /usr/bin/docker run -d --restart=always
    --name shard-$(cat /etc/hostname)
    --cpus="0.25"
    --memory="512m"
    -e MONGODB_SHARDING_MODE=shardsvr
    -e MONGODB_MONGOS_HOST=mongos
    -e MONGODB_ROOT_PASSWORD=password123
    -e MONGODB_REPLICA_SET_MODE=primary
    -e MONGODB_REPLICA_SET_KEY=replicasetkey123
    -e MONGODB_ADVERTISED_HOSTNAME=shard-$(cat /etc/hostname)
    -e MONGODB_REPLICA_SET_NAME=shard-$(cat /etc/hostname)
    bitnami/mongodb-sharded
  - echo kek
